version: '3.8'

services:
  redis:
    image: redis
    restart: always
    container_name: eliza-redis
    #command: bash -c "redis-server --requirepass password"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_eliza_volume:/data

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: eliza_redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_eliza_insight_volume_data:/db

volumes:
  redis_eliza_volume:
  redis_eliza_insight_volume_data:
